language: node_js

node_js:
  - stable

branches:
  only: master

install:
  - npm install istanbul -g
  - npm install  

script:
  - npm run test-coverage-generate
  - npm run test-coverage-remap
  - npm run test-coverage-send